apiVersion: v1
kind: Pod
metadata:
  name: postgre
  namespace: default
  labels:
    app: postgre
spec:
  containers:
  - name: postgre
    image: postgres:latest
    ports: 
    - containerPort: 5432
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
      requests:
        cpu: 0.25
        memory: 64Mi
    env:
      - name: POSTGRES_DB
        value: "playground"
      - name: POSTGRES_USER
        value: "app_user"
      - name: POSTGRES_PASSWORD
        value: "app_passw@rd"  


---

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: NodePort
  selector:
    app: postgre
  ports:
    - port: 5432
